### PR TITLE
feat: adds 'enum' and 'has_prefix' operators to 'metadata' condition

### PR DESCRIPTION
**Pull request by cludden**

### CODE REVIEW

**Comment by cludden** [comment]
took a stab at part I of #84, i feel like there has to be a better way of handling the interface{} `arg` field..

**Comment by Jeffail** [comment]
Hey @cludden, the rawJSONValue type is useful if we wanted to do function interpolation on the structure, or if the value could potentially be an arbitrary map (YAML would parse it as a map[interface{}]interface{} which is problematic). 

I think for this use case we can get away with just having an straight up `interface{}` type. When we construct the operator we either try to cast to `string`, or to `[]interface{}` and convert it into `[]string`.

I was thinking this morning that an alternative to a generic type here might be to have `arg string`
and `arg_list []string`, and then maybe `arg_map map[string]string` in the future if we ever needed that. This would allow us to have an explicit type (still limited to only strings) and also a cap on the number of fields as the operator list grows. What would be your thoughts on that approach?

**Comment by cludden** [comment]
i refactored this to use the empty `interface{}` type for arg, and included github.com/spf13/cast to allow individual operator factories to cast arg to complex types and avoid cluttering each operator with thorough [casting logic](https://github.com/spf13/cast/blob/master/caste.go#L1040). I debated the addition of this package, but with the bulk of configs likely being yaml, and all of the weirdness that comes with yaml parsing, it seemed like this could be useful to more operators if they require complex args. if you're opposed, let me know and I can take it out and inline all of the casting logic..

**Comment by Jeffail** [comment]
Looks great, I think that's reasonable. We ought to be aware that `cast` is very liberal when it comes to input validation, for example I believe the string "foo bar baz" would be parsed into a `[]string` without error, resulting in `[]string{"foo","bar","baz}`, but I'm not convinced this is likely to hurt anyone.

Are you ready for this to be merged? My only nag would be to change the tabs in your `yaml` snippets to spaces.

**Comment by cludden** [comment]
I did see that, but agreed that the impact is probably not harmful. I've gone ahead and fied the yaml whitespace as well. consistency is always good!

**Comment by Jeffail** [comment]
@cludden just noticed that the `has_prefix` operator parses into a slice. That would mean that if I have an `arg` of `"foo bar baz "` then this operator would pass for messages I wouldn't expect it to, such as "bargraph".

Got example test cases here:

``` go
		{
			name: "has_prefix neg 2",
			fields: fields{
				operator: "has_prefix",
				key:      "foo",
				part:     0,
				arg:      "foo bar baz",
			},
			arg: map[string]string{
				"foo": "barley",
			},
			want: false,
		},
		{
			name: "has_prefix pos 2",
			fields: fields{
				operator: "has_prefix",
				key:      "foo",
				part:     0,
				arg:      "foo bar baz",
			},
			arg: map[string]string{
				"foo": "foo bar bazley",
			},
			want: true,
		},
```

**Comment by cludden** [comment]
I refactored the operator to handle both `string` and `[]string` arg variants, which handles your test cases and but still supports checking against a list of prefixes. Does that work?

**Comment by Jeffail** [comment]
Yep, this is great. Ready for me to merge?

**Comment by cludden** [comment]
:+1:

**Comment by Jeffail** [comment]
Thanks @cludden!

**Pull request merged**
