### PR TITLE
#73: Feature/config version for cluster

### PR DESCRIPTION
**Pull request by ghballiet**
Adding `TargetVersion` to `KafkaBalanced` input type.

### CODE REVIEW

**Comment by ghballiet** [comment]
Linking - #73

**Comment by Jeffail** [comment]
Sorry @ghballiet, didn't notice your PR until it was too late.

**Comment by ghballiet** [comment]
No problem - I'll resolve conflicts.

**Comment by ghballiet** [comment]
Actually - it looks like this PR has some changes in it that aren't the right scope. I'll close and re-open.

**Comment by Jeffail** [comment]
All the changes are in, your TLS field is now in master and the version config is already done for `kafka_balanced`.

**Pull request closed without merging**
