### PR TITLE
#63: added client certificates config option

### PR DESCRIPTION
**Pull request by ghballiet**
Added a new config option, `ClientCertificates`, to `lib/util/tls/type.go`.

### CODE REVIEW

**Comment by ghballiet** [comment]
Looks like a failing test - working on a fix.

**Comment by Jeffail** [comment]
Don't worry about the test, it's a dumb one that I ought to change anyway. The config needs changing so that you specify a list of certificate file paths, then you read and load them in the Get call.

**Comment by Jeffail** [comment]
Rebase on master and that test is gone.

**Comment by ghballiet** [comment]
Perfect - will have a full update on this within the next hour.

**Comment by ghballiet** [comment]
@Jeffail tests are passing, let me know if the change looks like what you had in mind! 🙂

**Comment by Jeffail** [comment]
Look great, I've merged into a temporary branch for now as I also made a breaking change to the root CAS field. If you and @nwest1 could run it and make sure it works for your use case I'm happy to merge.

**Comment by Jeffail** [comment]
Branch is at: https://github.com/Jeffail/benthos/tree/feature/tls-configs

**Comment by ghballiet** [comment]
Taking a look at this now.

**Comment by ghballiet** [comment]
This is working for me!

**Pull request merged**
