### PR TITLE
Add MSSQL driver

### LINKED ISSUE #797: Can we get also a driver for MS sql server?
Hello, I would love to use benthos in a project using MS SQL server.

It would be really great if there was support also for this database driver.

Do you have any plans for it / Would it be hard to add support for it?

Cheers

### PR DESCRIPTION
**Pull request by mihaitodor**
Fixes #797.

I tested the output like so (might be worth adding some integration tests for this too, since only Postgres is covered  under `lib/test/integration`:

```shell
localhost> docker run --rm -it -e ACCEPT_EULA=Y -e SA_PASSWORD=ins4n3lyStrongP4ssword -p1433:1433 microsoft/mssql-server-linux
```

```shell
container> /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P ins4n3lyStrongP4ssword -Q "create table footable(data varchar(50) not null);"
```

```yaml
input:
  stdin:
    codec: lines
output:
  sql:
    driver: mssql
    data_source_name: "sqlserver://sa:ins4n3lyStrongP4ssword@localhost:1433?database=master"
    query: "insert into footable(data) values(?);"
    args:
      - ${! json("data") }
```

```shell
localhost> ./target/bin/benthos -c sql.yaml
{"data":"foo"}
```

```shell
container> /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P ins4n3lyStrongP4ssword -Q "select * from footable;"
foo

(1 rows affected)
```

### CODE REVIEW

**Comment by Jeffail** [comment]
Awesome, thanks @mihaitodor, can you do a quick check that this import doesn't break wasm builds? Just running `@GOOS=js GOARCH=wasm go build -ldflags="-s -w" ./cmd/benthos` should throw an error if it's broken. If it does break them then you'll need to add the import to `sql_extra.go` instead.

**Comment by mihaitodor** [comment]
@Jeffail I think I'm doing something wrong, because I can't get that to work even on the `master` branch. I tried both on OSX (go v1.16.5) and in the `golang:latest` Docker container and it keeps spewing a bunch of errors saying that the "non-pc-relative relocation address for ... is too big". I saw that some of them were caused by Pulsar and Google Storage, so I hid those behind some build tags, but that doesn't seem to be enough:

<details>
  <summary>Details</summary>

```
root@bc330741a172:/workspace# GOOS=js GOARCH=wasm go build -ldflags="-s -w" ./cmd/benthos
# github.com/Jeffail/benthos/v3/cmd/benthos
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentEqualsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentEqualsCondition).Check is too big: 0x101580000
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentEqualsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.ContentEqualsCondition.Check is too big: 0x101320000
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONContainsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentJSONContainsCondition).Check is too big: 0x101590000
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONContainsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONContainsCondition.Check is too big: 0x101350000
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONEqualsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentJSONEqualsCondition).Check is too big: 0x1015a0000
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONEqualsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONEqualsCondition.Check is too big: 0x101340000
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentMatchesCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentMatchesCondition).Check is too big: 0x1015b0000
type.github.com/Jeffail/benthos/v3/lib/service/test.ContentMatchesCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.ContentMatchesCondition.Check is too big: 0x101330000
type.*github.com/Jeffail/benthos/v3/internal/template.FieldConfig: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/internal/template.(*FieldConfig).FieldSpec is too big: 0x101930000
type.*github.com/Jeffail/benthos/v3/internal/template.FieldConfig: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/internal/template.(*FieldConfig).FieldSpec is too big: 0x101930000
type.*github.com/Jeffail/benthos/v3/internal/template.compiled: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/internal/template.(*compiled).ExpandToNode is too big: 0x101850000
type.*github.com/Jeffail/benthos/v3/internal/template.compiled: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/internal/template.(*compiled).ExpandToNode is too big: 0x101850000
type.*github.com/Jeffail/benthos/v3/lib/service/blobl.execCache: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/blobl.(*execCache).executeMapping is too big: 0x101a40000
type.*github.com/Jeffail/benthos/v3/lib/service/blobl.execCache: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/blobl.(*execCache).executeMapping is too big: 0x101a40000
type.*github.com/Jeffail/benthos/v3/lib/service/test.CaseFailure: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*CaseFailure).String is too big: 0x101550000
type.*github.com/Jeffail/benthos/v3/lib/service/test.CaseFailure: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*CaseFailure).String is too big: 0x101550000
type.*github.com/Jeffail/benthos/v3/lib/service/test.ContentEqualsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentEqualsCondition).Check is too big: 0x101580000
type.*github.com/Jeffail/benthos/v3/lib/service/test.ContentEqualsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentEqualsCondition).Check is too big: 0x101580000
type.*github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONContainsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentJSONContainsCondition).Check is too big: 0x101590000
type.*github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONContainsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentJSONContainsCondition).Check is too big: 0x101590000
type.*github.com/Jeffail/benthos/v3/lib/service/test.ContentJSONEqualsCondition: non-pc-relative relocation address for github.com/Jeffail/benthos/v3/lib/service/test.(*ContentJSONEqualsCondition).Check is too big: 0x1015a0000
/usr/local/go/pkg/tool/linux_amd64/link: too many errors
```

</details>

This is the fist time I tried to mess with wasm and I'm not really sure what the problem is. I read the docs that are linked in this [StackOverflow question](https://stackoverflow.com/questions/67294859/why-golang-limit-the-symbol-number-to-65535-while-compile-wasm-target) but they didn't enlighten me much.

Please let me know if you have any idea. Otherwise, I'll do some more digging.

**Comment by Jeffail** [comment]
Oh dang, yeah just tried it myself and something's clearly broken. Don't worry about it for now, it's only used for benthos labs so I can sort this out separately.

**Comment by mihaitodor** [comment]
OK, cool. I'll do a bit more reading too. Maybe it's not a huge issue to fix.

**Comment by mihaitodor** [comment]
@Jeffail I did a bisect and at least part of the issue is caused by 35072219. There are a bunch of updated libs in there, so I'll try to narrow it down.

**Comment by brandongilzean** [comment]
@mihaitodor  does this work with windows authentication?

**Comment by mihaitodor** [comment]
@brandongilzean I haven't tested that, but please test it if you have the necessary setup and let us know if you hit any issues. https://github.com/denisenkom/go-mssqldb is the library which handles the connection and I see they mention something about that [here](https://github.com/denisenkom/go-mssqldb/blob/35162394aa7974ac37c4b42ddb1c200f6b01ebac/README.md#common-parameters).

**Comment by brandongilzean** [comment]
Right @mihaitodor , i think we may need to allow for slashes in the query sqlserver://domain\some_user:StrongPass123@host:1433?database=test-db. I think since it's a string, the slash throws it off and creates extra slashes?

**Comment by mihaitodor** [comment]
@brandongilzean I'm not sure I get what you mean. Are you saying that the `query` parameter is rejecting valid SQL queries which contain slashes? If possible, please provide an example config which has issues.

**Comment by brandongilzean** [comment]
Yeah sure, my apologies. I may be wrong but here is an example:
 - sql:
              driver: mssql
              result_codec: json_array
              data_source_name: sqlserver://**DOMAIN\test_user**:Strongpass123@server:1433?database=test-db

{"@timestamp":"2021-06-29T11:01:50-04:00","@service":"benthos","component":"benthos","level":"ERROR","message":"Service closing due to: failed to create processor 'branch': failed to init processor 0: failed to prepare query: parse \"sqlserver:**_//DOMAIN\\\\test_user_**:Strongpass123@server:1433?database=test-db\": net/url: invalid userinfo"}

**Comment by mihaitodor** [comment]
@brandongilzean No worries! I wasn't sure what issue you were bumping in. Unfortunately, I don't have an environment to test this in so I want to make sure this is not an issue on the Bethos side.

I think the backslash somehow gets escaped to `\\` and then it gets into [some code](https://github.com/denisenkom/go-mssqldb/blob/045585d74f9069afe2e115b6235eb043c8047043/conn_str.go#L290) go-mssqldb which barfs because `\` isn't a valid character in an URL according to [this](https://go-review.googlesource.com/c/go/+/87038) which mentions RFC 3986.

I did some tests [here](https://play.golang.org/p/PbtB2B7o8M6) which make me think that URL escaping that backslash character might work.

Could you please do me a favour and test replacing `/` with `%09`? So something like `data_source_name: sqlserver://DOMAIN%09test_user:Strongpass123@server:1433?database=test-db`.

**Comment by brandongilzean** [comment]
Yeah that definitely works :) Thanks so kindly! Anything else you need me to do? I can also update the docs to just explain that as well or you can do it.

**Comment by mihaitodor** [comment]
Awesome, thank you very much for testing this! I'll raise a PR to document it.

**Comment by brandongilzean** [comment]
My pleasure!

**Comment by mihaitodor** [comment]
@brandongilzean I sent a fix for this issue in #811, so you should be able to use `sqlserver://DOMAIN\test_user:Strongpass123@server:1433?database=test-db` in the next release. Please open a new issue if you encounter any problems.

**Comment by Jeffail** [comment]
Thanks @mihaitodor! :heart:

**Pull request merged**
