### PR TITLE
MongoDB cache, processor + output components

### PR DESCRIPTION
**Pull request by nmbryant**
Adds cache, processor and output components for mongodb, @Jeffail what are your thoughts on these?

Closes: #393

### CODE REVIEW

**Comment by nmbryant** [comment]
Do you know why I am getting the stale docs error? I have tried running 'make docs' on my branch again, and I am not getting any changes.

**Comment by Jeffail** [comment]
Very cool, will do a proper review hopefully this weekend. I'm very close to having the first iteration of the new plugin APIs ready for the back end and this might be a good candidate for that as it'll specifically benefit us in places where we have lots of component types integrating with a common service, you don't need to worry about that for now as I can make the changes once it's merged.

Not sure about the docs error, but it the env var config looks like it doesn't match your schema which could explain why: https://github.com/Jeffail/benthos/pull/678/files#diff-da65c46c6e27240326baf5ab679ab0f6599443587b153dc17c2d5f7181d4bc97R805

**Comment by Jeffail** [comment]
Also I'm not particularly savvy with MongoDB so it'd be extra useful if you could flesh out the documentation with examples, explaining stuff like when/how to use the `filter_map` fields, etc.

**Comment by nmbryant** [comment]
@Jeffail Added some more details to the docs for the mongo maps and added an example. You can also look at mongodb_test.go in the processor package for more example cases and how it works. Looks like the stale docs error is still happening (though the checks still passed), it seems to have to do with a field containing the word 'filter'. I tried adding a new field with the name 'test' and it appeared in default.yaml, but when I changed the name to 'filter' it was no longer in that file.

**Comment by Jeffail** [comment]
@nmbryant, the CI error sounds like it's an existing issue getting exposed, I'll take care of it.

**Comment by Jeffail** [comment]
Hey @nmbryant just to keep you in the loop, I'm actively working on this, I've got an updated branch with your changes adapted to the new way of defining components: https://github.com/Jeffail/benthos/tree/mongo-support

There's a few more things I want to take a look at but it's close to being merged.

**Comment by nmbryant** [comment]
Great, thanks for the update. I'll take a look once it's all set and merged in, curious to see the new way to define the components.

**Comment by mallikvala** [comment]
@Jeffail @nmbryant Any ETA for this PR?

**Comment by Jeffail** [comment]
Hey @mallikvala, hopefully I'll have it merged in the next couple of days, then a proper release in a week or so. This next release is pretty large in scope as it's a major rework of some internals so I'll be looking for volunteers to test a release candidate.

**Comment by Jeffail** [comment]
Merged: https://github.com/Jeffail/benthos/commit/548033877e52f833d92a7c8d42228d2ea6e00cbb using the new internal APIs.

**Comment by mallikvala** [comment]
@Jeffail I can help you test. Please let me know

**Pull request closed without merging**
