### PR TITLE
Add NATS auth fields

### LINKED ISSUE #859: Authenticating with a credentials file in NATS resources
In addition to authentication with user and password and authentication with token, which both can be passed within the URL there are some other methods to authenticate against a NATS server:
* [Authenticating with an NKey](https://docs.nats.io/developing-with-nats/security/nkey)
* [Authenticating with a Credentials File](https://docs.nats.io/developing-with-nats/security/creds)

Is it planned to support another authentication method in the future? I would be interested using one of these methods, preferring the credentials file.

### PR DESCRIPTION
**Pull request by mihaitodor**
For NATS, NATS Streaming and Jetstream components the config now supports specifying either `nkey_file` or `user_credentials_file` to configure authentication.

Fixes #859.

I noticed that https://docs.nats.io/nats-server/configuration/securing_nats/jwt says "It is possible to mix JWT and NKEY/Account based Authentication/Authorization" but I'm not sure what they mean by that, since the client library doesn't seem to like having both an NKey and a User Credentials file specified (see [here](https://github.com/nats-io/nats.go/blob/42edba421f77623576fb914344321612944faff7/nats.go#L1242-L1244)).

TODO:
- [x] Is there a way to mark fields as mutually exclusive?
- [x] Test with NATS Streaming and Jetstream. I only tested these new options with plain NATS Server so far.

### CODE REVIEW

**Comment by Jeffail** [comment]
:heart_eyes: looks awesome. The package `lib/util/nats/auth` ought to live within `internal` as it's new but everything else looks dapper, docs are great. Right now there isn't a convenient way to express exclusivity with the docs APIs but I can look at adding that.

**Comment by mihaitodor** [comment]
Cool, thanks @Jeffail! I moved the lib as requested. Would be nice to have exclusivity in the docs API. In this case, it would warn users to not set both `nkey_file` and `user_credentials_file` and then pull hairs out :)

I did a bunch of tests with `nats-server`, `nats-streaming-server` and `nats-server -js` with `nkey_file` and they all seem to work. Note that a fairly new version of `nats-streaming-server` [is required](https://github.com/nats-io/nats-streaming-server/issues/1095) for NKey auth support.

I couldn't figure out how to configure JWT auth for `nats-streaming-server` and `nats-server -js` so I wasn't able to test that yet. When creating an account with their [nsc](https://docs.nats.io/nats-tools/nsc) tool, it looks like Jetstream is disabled by default for whatever reason and I don't see any flag to enable it:
```
nsc describe account -W
+--------------------------------------------------------------------------------------+
|                                   Account Details                                    |
+---------------------------+----------------------------------------------------------+
| Name                      | A                                                        |
| Account ID                | ABM7ZYEGANDF7VEKOYZMRXPQSBLGKAGGWLE4PETYUVSZEKYRUEH3RUQC |
| Issuer ID                 | OAVSYDNQHNBBZHB3E66BJEJ3MC2ZB2WV42WEVL7OV7RTT4W45PJ7E4MO |
| Issued                    | 2021-09-07 01:23:12 UTC                                  |
| Expires                   |                                                          |
+---------------------------+----------------------------------------------------------+
| Max Connections           | Unlimited                                                |
| Max Leaf Node Connections | Unlimited                                                |
| Max Data                  | Unlimited                                                |
| Max Exports               | Unlimited                                                |
| Max Imports               | Unlimited                                                |
| Max Msg Payload           | Unlimited                                                |
| Max Subscriptions         | Unlimited                                                |
| Exports Allows Wildcards  | True                                                     |
| Response Permissions      | Not Set                                                  |
+---------------------------+----------------------------------------------------------+
| Jetstream                 | Disabled                                                 |
+---------------------------+----------------------------------------------------------+
| Imports                   | None                                                     |
| Exports                   | None                                                     |
+---------------------------+----------------------------------------------------------+
```

For `nats-streaming-server` it seems that it refuses to connect to the embedded NATS when I try to use a JWT config...

At least I can confirm that plain `nats-server` does start up with this JWT I created and Benthos can connect to it and read messages if `user_credentials_file` is set.

I can try to do some extra digging for the other two if you'd like.

**Comment by Jeffail** [comment]
Awesome, I'm happy to proceed as is, I'll maybe mark the fields as beta until we have prod users happy with it, maybe @KairaMiu can try it out and report back once it's released.

**Comment by mihaitodor** [comment]
Ugh, I managed to screw up the rebase and ended up taking over a commit you made 🤦‍♂️ I'm surprised it merged cleanly. I swear I had a nice commit message in there...

**Comment by KairaMiu** [comment]
@Jeffail @mihaitodor works like a charm! Thanks for this great feature!

**Pull request merged**
