### PR TITLE
first pass at influx metrics reporting

### PR DESCRIPTION
**Pull request by nwest1**
Hello!

I wanted to get a working first pass in before some of the testing I was planning on doing, but wanted to get a little feedback about style and had a few questions:
- Is the metrics.Local good enough for now or should I look to add some more features around timing metrics? Similar to the prometheus count/sum/latency and the quantile bucketing? 
- Possibly look into using https://github.com/rcrowley/go-metrics as a backing instead?

I probably should have created an issue first, but I wanted to validate I could get it mostly working. Hopefully this fits! 

Edit: 
- adding latest metrics/config
- adding runtime / gc metrics 

*config*
```yaml
http:
  enabled: false
input:
  type: stdin
pipeline:
  processors:
    - bloblang: |
        root.a = this.a.not_null()
    - metric:
        type: counter
        name: "sample"
        labels:
          topic: "topicvalue"
  threads: 1
output:
  type: stdout
metrics:
  type: influxdb
  influxdb:
    interval: 10s
    include:
      runtime: 10s
      debug_gc: 10s
    tags:
      host: localhost1
    path_mapping: 'root = "benthos." + this'
```

*ILP output*
```
benthos.debug.GCStats.LastGC,host=localhost1 value=1607096219343850000i 1607096249342228000
benthos.debug.GCStats.NumGC,host=localhost1 value=8i 1607096249342228000
benthos.debug.GCStats.PauseTotal,host=localhost1 value=707328i 1607096249342228000
benthos.debug.ReadGCStats,host=localhost1 15m.rate=0.0021916080095982747,1m.rate=0.027166432447264945,5m.rate=0.006395558561741572,count=2i,max=35929i,mean=19314,mean.rate=0.06674081909599246,min=2699i,p50=19314,p75=35929,p95=35929,p99=35929,p999=35929,stddev=16615 1607096249342228000
benthos.input.batch.received,host=localhost1 count=0i 1607096249342228000
benthos.input.connection.failed,host=localhost1 count=33i 1607096249342228000
benthos.input.connection.lost,host=localhost1 count=0i 1607096249342228000
benthos.input.connection.up,host=localhost1 count=0i 1607096249342228000
benthos.input.count,host=localhost1 count=0i 1607096249342228000
benthos.input.latency,host=localhost1 15m.rate=0,1m.rate=0,5m.rate=0,count=0i,max=0i,mean=0,mean.rate=0,min=0i,p50=0,p75=0,p95=0,p99=0,p999=0,stddev=0 1607096249342228000
benthos.input.received,host=localhost1 count=0i 1607096249342228000
benthos.input.running,host=localhost1 value=1i 1607096249342228000
benthos.output.batch.bytes,host=localhost1 count=0i 1607096249342228000
benthos.output.batch.latency,host=localhost1 15m.rate=0,1m.rate=0,5m.rate=0,count=0i,max=0i,mean=0,mean.rate=0,min=0i,p50=0,p75=0,p95=0,p99=0,p999=0,stddev=0 1607096249342228000
benthos.output.batch.sent,host=localhost1 count=0i 1607096249342228000
benthos.output.count,host=localhost1 count=0i 1607096249342228000
benthos.output.sent,host=localhost1 count=0i 1607096249342228000
benthos.runtime.MemStats.Alloc,host=localhost1 value=6447064i 1607096249342228000
benthos.runtime.MemStats.BuckHashSys,host=localhost1 value=1459643i 1607096249342228000
benthos.runtime.MemStats.DebugGC,host=localhost1 value=0i 1607096249342228000
benthos.runtime.MemStats.EnableGC,host=localhost1 value=1i 1607096249342228000
benthos.runtime.MemStats.Frees,host=localhost1 value=163i 1607096249342228000
benthos.runtime.MemStats.GCCPUFraction,host=localhost1 value=0.035881684235192175 1607096249342228000
benthos.runtime.MemStats.HeapAlloc,host=localhost1 value=6447064i 1607096249342228000
benthos.runtime.MemStats.HeapIdle,host=localhost1 value=57860096i 1607096249342228000
benthos.runtime.MemStats.HeapInuse,host=localhost1 value=8232960i 1607096249342228000
benthos.runtime.MemStats.HeapObjects,host=localhost1 value=34096i 1607096249342228000
benthos.runtime.MemStats.HeapReleased,host=localhost1 value=53944320i 1607096249342228000
benthos.runtime.MemStats.HeapSys,host=localhost1 value=66093056i 1607096249342228000
benthos.runtime.MemStats.LastGC,host=localhost1 value=1607096219343850000i 1607096249342228000
benthos.runtime.MemStats.Lookups,host=localhost1 value=0i 1607096249342228000
benthos.runtime.MemStats.MCacheInuse,host=localhost1 value=20832i 1607096249342228000
benthos.runtime.MemStats.MCacheSys,host=localhost1 value=32768i 1607096249342228000
benthos.runtime.MemStats.MSpanInuse,host=localhost1 value=217192i 1607096249342228000
benthos.runtime.MemStats.MSpanSys,host=localhost1 value=245760i 1607096249342228000
benthos.runtime.MemStats.Mallocs,host=localhost1 value=2385i 1607096249342228000
benthos.runtime.MemStats.NextGC,host=localhost1 value=10925072i 1607096249342228000
benthos.runtime.MemStats.NumGC,host=localhost1 value=0i 1607096249342228000
benthos.runtime.MemStats.PauseTotalNs,host=localhost1 value=707328i 1607096249342228000
benthos.runtime.MemStats.StackInuse,host=localhost1 value=1015808i 1607096249342228000
benthos.runtime.MemStats.StackSys,host=localhost1 value=1015808i 1607096249342228000
benthos.runtime.MemStats.Sys,host=localhost1 value=77153280i 1607096249342228000
benthos.runtime.MemStats.TotalAlloc,host=localhost1 value=32016000i 1607096249342228000
benthos.runtime.NumCgoCall,host=localhost1 value=20i 1607096249342228000
benthos.runtime.NumGoroutine,host=localhost1 value=15i 1607096249342228000
benthos.runtime.NumThread,host=localhost1 value=16i 1607096249342228000
benthos.runtime.ReadMemStats,host=localhost1 15m.rate=0.0021916080095982747,1m.rate=0.027166432447264945,5m.rate=0.006395558561741572,count=3i,max=236868i,mean=149699.66666666666,mean.rate=0.09999919560647054,min=91477i,p50=120754,p75=236868,p95=236868,p99=236868,p999=236868,stddev=62785.47833341365 1607096249342228000
```

*input sample*
```
{"a":"something"}
{"b":"something else"}
```

### CODE REVIEW

**Review by Jeffail — COMMENTED** [review]
Hey @nwest1, left a couple of comments but at a glance it looks like a good start. Would it make sense to target 1.8+ with https://github.com/influxdata/influxdb-client-go? I'm not familiar with influx so I don't know how common versions older than 1.8 are in the wild.

> Is the metrics.Local good enough for now or should I look to add some more features around timing metrics? Similar to the prometheus count/sum/latency and the quantile bucketing?

Yeah looks like we'll need bucketing here, I definitely wouldn't want to release this in a state where timing metrics were discarded.

Ignore the CI error, I'll disable the docker dry runs since we can't authenticate them on PRs.

**Comment by nwest1** [comment]
I'll look into using the 1.8+ library. 

Internally, we use a `/write` endpoint (1.x endpoint, 2.0 forward-compatible) so would prefer to target that instead. If that library is supportive, I'll definitely change it over. If there is 1.x/1.8+ separation, would you prefer a different metrics type or a config parameter?

After a few days off here, I'll leverage go-metrics to achieve some of that bucketing.

Thanks for the feedback!

**Comment by nwest1** [comment]
Hey @Jeffail ! I've added some tests, pulled in the go-metrics registry to back the metrics that are generated. 

I did test out the newer client internally, but unfortunately we won't be supporting that for awhile.

I did add a potential option here for the latest library: https://github.com/nwest1/benthos/compare/metrics-influx...nwest1:influxv2?expand=1
Let me know what you think about naming (`influx` -> `influxv2`) or if it should be something else. Or any other possibilities for reuse you see. 

That `influxv2` branch needs some cleanup - mainly to remove the client options that don't make sense for the blocking write. It made sense for me to use the blocking vs. non because it's running in the background anyway, so I didn't want to complicate it further. Let me know if you think differently. 

Thanks for your time!

**Comment by Jeffail** [comment]
Hey @nwest1, this is looking really nice. One missing part is the ability to define path mappings which allows users to filter and rename metrics that are registered. You can see an example here: https://github.com/Jeffail/benthos/blob/9768b9b6e4fac1e5eb3d260878edb401188adc72/lib/metrics/cloudwatch.go#L293

It's unfortunately a bit of a drag as you have to add it to each method, I'm planning to clean a lot of this stuff up in future but I've struggled as it still needs to be backwards compatible.

**Comment by nwest1** [comment]
The latest update summary:
- added path mapping 
- added option for go runtime and gc metrics to be collected (similar to prometheus' built-in, but leveraging go-metrics)
- rename `Influx`/`influx` to `InfluxV1`/`influxv1` - I figured v1 will be more of an exception and v2 to be more standard as time goes on.
- overriding any existing tags with the globally-defined ones, as that is the behavior in the v2 influx client.
- moved the prefixing to metrics output, so that any metrics gathered along the way (bloblang, processor, runtime collectors) would be correctly prefixed. Based on config location, it seems like a global application would be expected behavior. I know the prometheus output does not behave that way, but let me know what you think.

**Comment by Jeffail** [comment]
Awesome, implementation looks good to go. I think for naming it would probably sit better with the existing components if we called this `influxdb`, and when we add v2 we call that `influxdb_v2`. I'm also considering removing `prefix` entirely in the next major version of Benthos, as you can add your own prefix with `path_mapping: 'root = "benthos." + this'` if you wanted, which avoids the confusion about ordering, etc. We could try that out here first.

Also the new fields for including runtime and debug metrics could probably do with being in their own config block, maybe something like:

```yaml
metrics:
  type: influxdb
  influxdb:
    interval: 10s
    include:
      runtime: 10s
      debug_gc: 10s
    tags:
      host: localhost
```

Where they default to an empty string (to indicate exclusion).

Sorry to add more stuff on the pile, I'll aim to make these changes myself at some point this week unless you beat me to it, and then it's a straight road to merge city.

**Comment by nwest1** [comment]
This config definition is important. And usually don't discover the optimal until closer to the end if you're lucky.

I'm working on getting the path mapping working properly with the runtime metrics - and discovering a few bugs along the way. Should have something later today. Thanks again!

**Comment by nwest1** [comment]
One last fix to the integration test that would have otherwise failed on merge. Let me know if you see anything else to improve!

**Comment by Jeffail** [comment]
Awesome, thanks @nwest1! I'm going to mark this as experimental for now just to give others a chance to try it out and give feedback.

**Pull request merged**
